# 開発環境構築用

version: '3'

services:
  web: &web
    build:
      context: .
      dockerfile: docker/development/Dockerfile.slim
    volumes:
      - bundler:/usr/local/bundle
      - /usr/src/app/tmp/pids
      - .:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    links:
      - db
    depends_on:
      - db
    environment:
      WEBPACKER_DEV_SERVER_HOST: 0.0.0.0
    # NOTE: 下記はbinding.pryをしたときに docker attach して入力するために必要な設定
    tty: true
    stdin_open: true

  db:
    image: mariadb
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - db:/var/lib/mysql
    ports:
      - "${DB_PORT:-3306}:3306"

  nginx:
    build:
      context: docker/development/nginx
    volumes:
      - ./docker/development/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/development/nginx/ssl:/etc/nginx/ssl
    ports:
      - 443:443
    links:
      - web

volumes:
  bundler: {}
  node_modules: {}
  db: {}
